Repository Jigsaw-Code/outline-apps, pull requests merged in 2021-02, with the labels that each got.

#958 Use verbose logging in ss-local and tun2socks when in Debug mode
  src/electron/index.ts
  src/electron/process_manager.ts
Labels: Fixit 2021 Q1, failure/connect, failure/connectivity

#965 bump ssconfig version number
  package.json
  yarn.lock
Labels: Fixit 2021 Q1

#961 Tell Sentry the app name from the renderer process
  src/electron/index.ts
  src/www/app/electron_main.ts
  src/www/app/main.ts
Labels: Fixit 2021 Q1, build issue

#963 update some git dep version tags that were failing, and run yarn upgrade
  package.json
  yarn.lock
Labels: Fixit 2021 Q1

#974 Don't log to Sentry in debug mode
  src/electron/electron_main.webpack.js
  src/electron/go_vpn_tunnel.ts
  src/electron/process.ts
  src/electron/sslibev_badvpn_tunnel.ts
Labels: Fixit 2021 Q1, os/linux, os/windows
