Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-06, with the labels that each got.

#1326 fix(devtools): allow ambient modules
  .eslintignore
  .eslintrc.json
  src/electron/tsconfig.json
  src/tslint.json
  src/types/ambient/shims.d.ts
  src/www/storybook.action.sh
  src/www/tsconfig.json
  src/www/views/servers_view/server_connection_indicator/index.ts
  src/www/web-dev-server.config.mjs
  src/www/webpack_base.mjs
  src/www/webpack_cordova.mjs
  src/www/webpack_electron.mjs
  src/www/webpack_test.mjs
  tsconfig.json
Labels: size/M

#1274 fix(electron): 💊 fix routing daemon installation issue in Linux
  src/electron/index.ts
  src/electron/routing_service.ts
  src/electron/sslibev_badvpn_tunnel.ts
  src/electron/util.ts
  src/www/app/app.ts
  src/www/app/cordova_main.ts
  src/www/app/electron_main.ts
  src/www/app/main.ts
  src/www/app/platform.ts
  src/www/app/vpn_installer.ts
  src/www/messages/en.json
Labels: os/windows, os/linux, size/L

#1336 feat(www): 🌐 prepare translations for newly added messages
  resources/original_messages.json
  src/www/messages/en.json
Labels: size/XS

#1338 fix(cordova/apple/ios): reset signing
  src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
Labels: size/XS

#1341 fix: breaking ios issues and update ios version
  src/cordova/apple/xcode/ios/Outline/Outline-Info.plist
  src/www/ui_components/about-view.js
  src/www/ui_components/app-root.js
  src/www/ui_components/language-view.js
  src/www/ui_components/privacy-view.js
  src/www/views/servers_view/server_list_item/server_card/index.ts
Labels: size/S

#1342 build(cordova/apple/macos): signing reset and version bump
  src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist
  src/cordova/apple/xcode/osx/Outline.xcodeproj/project.pbxproj
  src/cordova/apple/xcode/osx/Outline/VpnExtension-Info.plist
Labels: size/XS

#1337 feat(devtools): restrict invalid import paths
  .eslintrc.json
  package-lock.json
  package.json
Labels: size/XS

#1345 fix(docs): create invitation-instructions.md link-through
  docs/invitation-instructions.md
Labels: size/XS

#1351 refactor: intrastructure, types, and cordova macos folder
  .eslintrc.json
  src/build/get_build_number.mjs
  src/build/get_version.mjs
  src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  src/cordova/apple/xcode/macos/Outline.xcodeproj/xcshareddata/xcschemes/Outline.xcscheme
  src/cordova/apple/xcode/macos/Outline.xcodeproj/xcshareddata/xcschemes/OutlineLauncher.xcscheme
  src/cordova/apple/xcode/macos/Outline.xcodeproj/xcshareddata/xcschemes/VpnExtension.xcscheme
  src/cordova/apple/xcode/macos/Outline/Classes/AppDelegate.m
  src/cordova/apple/xcode/macos/Outline/Classes/CDVMacOsUrlHandler.swift
  src/cordova/apple/xcode/macos/Outline/Classes/EventMonitor.swift
  src/cordova/apple/xcode/macos/Outline/Images.xcassets/StatusBarButtonImage.imageset/Contents.json
  src/cordova/apple/xcode/macos/Outline/Images.xcassets/StatusBarButtonImage.imageset/outline-black-off-2x.png
  src/cordova/apple/xcode/macos/Outline/Images.xcassets/StatusBarButtonImageConnected.imageset/Contents.json
  src/cordova/apple/xcode/macos/Outline/Images.xcassets/StatusBarButtonImageConnected.imageset/outline-black-on-2x.png
  src/cordova/apple/xcode/macos/Outline/MainViewController.xib
  src/cordova/apple/xcode/macos/Outline/Outline-Info.plist
  src/cordova/apple/xcode/macos/Outline/Outline.entitlements
  src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist
  src/cordova/apple/xcode/macos/Outline/VpnExtension.entitlements
  src/cordova/apple/xcode/macos/Outline/config.xml
  src/cordova/apple/xcode/macos/OutlineLauncher/AppDelegate.swift
  src/cordova/apple/xcode/macos/OutlineLauncher/Base.lproj/Main.storyboard
  src/cordova/apple/xcode/macos/OutlineLauncher/Info.plist
  src/cordova/apple/xcode/macos/OutlineLauncher/OutlineLauncher.entitlements
  src/cordova/apple/xcode/macos/osx.json
  src/cordova/apple/xcode/macos/www/cordova_plugins.js
  src/cordova/setup.action.mjs
  src/electron/types/electron-promise-ipc/index.d.ts
  src/electron/types/socks/index.d.ts
  src/electron/types/sudo-prompt/index.d.ts
  src/infrastructure/memory_storage.ts
  src/www/app/clipboard.ts
  src/www/app/cordova_main.ts
  src/www/app/outline_server.spec.ts
  src/www/app/settings.spec.ts
  src/www/app/url_interceptor.ts
  src/www/types/clipboard.d.ts
  src/www/types/shims.d.ts
  src/www/types/webintents.d.ts
Labels: code health, size/M

#1353 fix(www): empty name, body inset, list padding
  src/www/style.css
  src/www/views/servers_view/index.ts
  src/www/views/servers_view/server_connection_indicator/index.ts
  src/www/views/servers_view/server_list_item/server_card/index.ts
Labels: bug, size/XS
