Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-02, with the labels that each got.

#1185 👷 build(windows): pass the correct electron-builder argument for Windows
  scripts/get_electron_build_flags.mjs
Labels: bug

#1187 👷 build(windows): introduce Windows release pipeline
  .github/workflows/build_release_candidates.yml
  .github/workflows/build_windows_release_candidate.yml
Labels: release process

#1180 fix(release): catch invalid sentry DSN
  scripts/environment_json.mjs
Labels: bug, release process
