Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-05, with the labels that each got.

#1298 🎨 style(app): prettier format code files of #1274
  src/www/app/app.ts
  src/www/app/electron_main.ts
  src/www/app/electron_outline_tunnel.ts
  src/www/app/main.ts
  src/www/app/platform.ts
  src/www/model/errors.ts
Labels: code health

#1286 💊 fix(electron): fix wrong connection status when error is thrown during connect
  src/electron/index.ts
  src/electron/routing_service.ts
Labels: os/windows, os/linux

#1294 refactor(actions): renaming platform osx to macos
  .github/workflows/build_and_test_debug.yml
  scripts/get_build_parameters.mjs
  scripts/get_cordova_build_parameters.mjs
  src/cordova/build.action.mjs
  src/cordova/setup.action.mjs
Labels: release process

#1308 chore(macos): update version and remove overrides
  src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
Labels: os/macos

#1301 feat(devtools): pull request checks
  .github/workflows/pull_request_checks.yml
  commitlint.config.js
  package-lock.json
  package.json
Labels: code health, size/S

#1303 fix(www): restore initial indicator appearance
  src/www/views/servers_view/server_card/stories.ts
  src/www/views/servers_view/server_connection_indicator/index.ts
  src/www/views/servers_view/server_connection_indicator/stories.ts
  src/www/views/servers_view/server_list/stories.ts
Labels: bug

#1306 feat(devtools): browserslist
  .browserslistrc
  package-lock.json
  package.json
Labels: code health, size/XS

#1302 chore(docs): documentation rearrangement
  .github/workflows/build_and_test_debug.yml
  .travis.yml
  README.md
  commitlint.config.js
  docs/android-development.md
  docs/android_development.md
  docs/apple_development.md
  docs/electron_development.md
  docs/invitation_instructions.md
  package-lock.json
  package.json
  src/cordova/setup.action.mjs
Labels: code health, size/L

#1307 feat(devtools): eslint
  .eslintignore
  .eslintrc.json
  .github/workflows/build_and_test_debug.yml
  package-lock.json
  package.json
  src/cordova/setup.action.mjs
  src/electron/go_vpn_tunnel.ts
  src/electron/index.ts
  src/electron/routing_service.ts
  src/electron/sslibev_badvpn_tunnel.ts
  src/types/modules/electron-promise-ipc/index.d.ts
  src/www/app/app.ts
  src/www/app/clipboard.ts
  src/www/app/cordova_main.ts
  src/www/app/electron_outline_tunnel.ts
  src/www/app/fake_net.ts
  src/www/app/fake_tunnel.ts
  src/www/app/main.ts
  src/www/app/settings.spec.ts
  src/www/app/url_interceptor.ts
  src/www/app/util.ts
  src/www/infrastructure/memory_storage.ts
  src/www/model/events.ts
  src/www/views/servers_view/index.ts
Labels: code health, size/M

#1310 chore(devtools): outline letterhead
  list.action.mjs
  scripts/run_action.mjs
Labels: size/XS, fun

#1316 fix(www): missing indicator width
  scripts/run_action.mjs
  src/electron/build.action.sh
  src/www/views/servers_view/server_card/index.ts
Labels: bug, size/XS

#1317 chore(docs): fix Apple documentation
  docs/apple_development.md
Labels: size/XS

#1314 feat(devtools): eslint compat
  .eslintrc.json
  package-lock.json
  package.json
Labels: code health, release process, size/XS

#1315 chore(build): create src/build
  commitlint.config.js
  package.json
  src/build/get_build_environment.mjs
  src/build/get_build_number.mjs
  src/build/get_build_parameters.mjs
  src/build/get_root_dir.mjs
  src/build/get_version.mjs
  src/build/get_webpack_build_mode.mjs
  src/build/run_action.mjs
  src/cordova/build.action.mjs
  src/cordova/get_cordova_build_parameters.mjs
  src/cordova/setup.action.mjs
  src/electron/build.action.sh
  src/electron/get_electron_build_flags.mjs
  src/electron/start.action.sh
  src/www/build.action.mjs
  src/www/start.action.sh
Labels: release process, size/S

#1318 fix(devtools): remove plugins folder on cordova setup
  src/cordova/setup.action.mjs
Labels: build issue, size/XS

#1312 style(www): 🎨 format the code related to server and app
  src/www/app/electron_main.ts
  src/www/app/outline_server.ts
  src/www/app/tunnel.ts
  src/www/model/server.ts
Labels: size/S

#1322 fix(devtools): revert 'remove plugins folder on cordova setup'
  src/cordova/setup.action.mjs
Labels: build issue, size/XS

#1325 style(www): 🎨 format app-root.js
  src/www/ui_components/app-root.js
Labels: size/M

#1327 fix(electron/linux): 💊 outline icon is not shown in Ubuntu Dock
  src/electron/electron-builder.json
  src/electron/index.ts
Labels: os/linux, size/XS

#1282 chore(www): migrate `server-card` to lit
  package-lock.json
  package.json
  src/www/.storybook/localize.ts
  src/www/.storybook/preview-head.html
  src/www/.storybook/preview.js
  src/www/app/app.ts
  src/www/assets/material_icons.woff2
  src/www/index_electron.html
  src/www/style.css
  src/www/ui_components/app-root.js
  src/www/views/servers_view/index.ts
  src/www/views/servers_view/server_card/index.ts
  src/www/views/servers_view/server_card/stories.ts
  src/www/views/servers_view/server_connection_indicator/index.ts
  src/www/views/servers_view/server_connection_indicator/stories.ts
  src/www/views/servers_view/server_list/index.ts
  src/www/views/servers_view/server_list/stories.ts
  src/www/views/servers_view/server_list_item/index.ts
  src/www/views/servers_view/server_list_item/server_card/index.ts
  src/www/views/servers_view/server_list_item/server_card/stories.ts
  src/www/webpack_base.mjs
  src/www/webpack_electron.mjs
  src/www/webpack_test.mjs
  web-dev-server.config.mjs
Labels: code health, dependencies, size/XXL

#1323 feat(www): 🌐 introduce new i18n languages support
  .github/workflows/pull_request_checks.yml
  src/www/messages/bs.json
  src/www/messages/en-GB.json
  src/www/messages/es.json
  src/www/messages/et.json
  src/www/messages/fa.json
  src/www/messages/hy.json
  src/www/messages/ka.json
  src/www/messages/mk.json
  src/www/messages/my.json
  src/www/messages/pt-BR.json
  src/www/messages/pt-PT.json
  src/www/messages/sq.json
  src/www/ui_components/app-root.js
Labels: size/XS
