Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-09, with the labels that each got.

#1401 refactor(www): move ShadowsocksSessionConfig to tunnel.ts
  src/electron/go_vpn_tunnel.ts
  src/electron/index.ts
  src/electron/sslibev_badvpn_tunnel.ts
  src/electron/tunnel_store.ts
  src/www/app/config.ts
  src/www/app/cordova_main.ts
  src/www/app/electron_outline_tunnel.ts
  src/www/app/fake_tunnel.ts
  src/www/app/outline_server_repository/access_key_serialization.ts
  src/www/app/outline_server_repository/index.ts
  src/www/app/outline_server_repository/outline_server_repository.spec.ts
  src/www/app/outline_server_repository/server.ts
  src/www/app/tunnel.ts
Labels: size/L

#1403 chore: update Outline client version to 1.7.3 for all platforms
  config.xml
  src/build/get_version.mjs
  src/cordova/apple/xcode/ios/Outline/Outline-Info.plist
  src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist
  src/cordova/apple/xcode/macos/Outline/Outline-Info.plist
  src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist
Labels: size/XS

#1407 fix(build): 🚧 fix `buildMode` typo in cordova build script
  src/cordova/build.action.mjs
Labels: build issue, size/XS
