Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-10, with the labels that each got.

#1421 fix(cordova/android): fix apk release script
  .gitignore
  src/cordova/build.action.mjs
Labels: size/XS

#1414 fix(www): adds basic server connection toggle timeouts
  src/www/app/app.ts
Labels: size/XS

#1423 chore: update Outline client version to 1.8.0 for all platforms
  config.xml
  src/build/get_version.mjs
  src/cordova/apple/xcode/ios/Outline/Outline-Info.plist
  src/cordova/apple/xcode/macos/Outline/Outline-Info.plist
Labels: size/XS

#1427 fix(www): 💊 `localize` is not initialized during `syncServersToUI`
  src/www/app/app.ts
Labels: size/XS

#1424 feat(devtools): add link to mattermost channel
  README.md
Labels: size/XS

#1426 build(electron/windows): 👷 add option to use GCP KMS for signing
  src/build/run_action.mjs
  src/build/spawn_stream.mjs
  src/electron/windows/electron_builder_signing_plugin.cjs
  src/electron/windows/sign_windows_executable.action.mjs
  third_party/jsign/METADATA
  third_party/jsign/jsign-4.0.jar
  third_party/jsign/jsign-4.2.jar
Labels: os/windows, size/S

#1434 chore: update android build number to 41
  config.xml
Labels: size/XS

#1439 fix(devtools): add publish config url so we can get proper client updates
  src/electron/build.action.mjs
  src/electron/get_electron_build_parameters.mjs
Labels: size/XS

#1445 feat(www): dynamic key text body support
  src/www/app/outline_server_repository/access_key_serialization.ts
  src/www/app/outline_server_repository/server.ts
  src/www/model/errors.ts
  src/www/views/servers_view/server_list_item/server_card/index.ts
Labels: size/S

#1442 feat(www): add alternate link in farsi
  src/www/messages/en.json
  src/www/messages/fa.json
  src/www/ui_components/add-server-view.js
  src/www/ui_components/app-root.js
  src/www/views/servers_view/index.ts
Labels: size/S

#1455 refactor(electron): ♻️ use async model for ChildProcessHelper
  src/electron/go_vpn_tunnel.ts
  src/electron/process.ts
Labels: size/L
