Repository Jigsaw-Code/outline-apps, pull requests merged in 2022-08, with the labels that each got.

#1373 chore(docs): update linux installation instructions
  docs/invitation_instructions.md
Labels: size/XS

#1374 fix: add exec step to linux install
  docs/invitation_instructions.md
Labels: size/XS

#1365 refactor(electron): ♻️ a huge upgrade to electron 19.0.8
  .eslintrc.json
  package-lock.json
  package.json
  src/electron/build_main.action.mjs
  src/electron/index.ts
  src/electron/preload.d.ts
  src/electron/preload.ts
  src/electron/webpack_electron_main.mjs
  src/www/app/electron_main.ts
  src/www/app/electron_outline_tunnel.ts
  src/www/index_electron.html
Labels: os/windows, dependencies, os/linux, size/L

#1382 chore: update codeowners
  .github/CODEOWNERS
Labels: size/XS

#1391 fix(build): don't run the size label on forks
  .github/workflows/pull_request_checks.yml
Labels: size/XS

#1388 chore(www): create outline_server_repository folder
  .eslintrc.json
  src/electron/connectivity.ts
  src/electron/go_vpn_tunnel.ts
  src/electron/routing_service.ts
  src/electron/sslibev_badvpn_tunnel.ts
  src/infrastructure/custom_error.ts
  src/infrastructure/electron/app_paths.ts
  src/infrastructure/timeout_promise.ts
  src/www/app/app.ts
  src/www/app/main.ts
  src/www/app/outline_server_repository/access_key_serialization.ts
  src/www/app/outline_server_repository/index.ts
  src/www/app/outline_server_repository/outline_server_repository.spec.ts
  src/www/app/outline_server_repository/server.ts
  src/www/model/errors.ts
Labels: size/L
