Repository Jigsaw-Code/outline-apps, pull requests merged in 2023-01, with the labels that each got.

#1528 chore(docs): update Android setup instructions
  .github/workflows/build_and_test_debug.yml
  .java-version
  src/cordova/android/README.md
  tools/build/android_tools_versions.sh
  tools/build/setup_linux_android.sh
  tools/build/setup_macos_android.sh
Labels: size/M

#1537 build(electron/windows): 👷 exclude jsign.jar from the repository
  package-lock.json
  package.json
  src/build/download_file.mjs
  src/build/get_file_checksum.mjs
  src/electron/windows/sign_windows_executable.action.mjs
  third_party/jsign/.gitignore
  third_party/jsign/index.mjs
  third_party/jsign/jsign-4.2.jar
Labels: size/S

#1540 chore(cordova/android): make an Android library
  src/cordova/android/OutlineAndroidLib/.gitignore
  src/cordova/android/OutlineAndroidLib/build.gradle
  src/cordova/android/OutlineAndroidLib/gradle.properties
  src/cordova/android/OutlineAndroidLib/gradle/wrapper/gradle-wrapper.jar
  src/cordova/android/OutlineAndroidLib/gradle/wrapper/gradle-wrapper.properties
  src/cordova/android/OutlineAndroidLib/gradlew
  src/cordova/android/OutlineAndroidLib/gradlew.bat
  src/cordova/android/OutlineAndroidLib/outline/.gitignore
  src/cordova/android/OutlineAndroidLib/outline/build.gradle
  src/cordova/android/OutlineAndroidLib/outline/consumer-rules.pro
  src/cordova/android/OutlineAndroidLib/outline/proguard-rules.pro
  src/cordova/android/OutlineAndroidLib/outline/src/androidTest/java/org/outline/vpn/VpnTunnelStoreTest.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/AndroidManifest.xml
  src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
  src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/TunnelConfig.aidl
  src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/shadowsocks/ShadowsocksConfig.aidl
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/log/OutlineLogger.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/log/SentryErrorReporter.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnServiceStarter.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnel.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelStore.java
  src/cordova/android/OutlineAndroidLib/outline/src/test/java/org/outline/vpn/VpnTunnelTest.java
  src/cordova/android/OutlineAndroidLib/settings.gradle
  src/cordova/android/README.md
  src/cordova/build.action.mjs
  src/cordova/plugin/android/java/build-extras.gradle
  src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
  src/cordova/plugin/plugin.xml
Labels: size/XL
