Repository Jigsaw-Code/outline-apps, pull requests merged in 2023-10, with the labels that each got.

#1733 feat(www): send form feedback from new contact view via Sentry
  src/www/TODO.spec.ts
  src/www/app/app.ts
  src/www/app/cordova_main.ts
  src/www/app/electron_main.ts
  src/www/app/platform.ts
  src/www/shared/error_reporter.ts
  src/www/ui_components/app-root.js
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
  src/www/views/contact_view/stories.ts
  src/www/views/contact_view/support_form/index.spec.ts
  src/www/views/contact_view/support_form/index.ts
  src/www/views/contact_view/support_form/stories.ts
Labels: size/M

#1736 feat(www): change which issue types are shown in new contact view based on the variant
  resources/original_messages.json
  src/www/messages/en.json
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
  src/www/views/contact_view/issue_type.ts
Labels: size/S, missing translations

#1737 fix(www): reset the contact view if the user navigates back
  src/www/ui_components/app-root.js
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
Labels: size/XS

#1742 fix(www): use `querySelector` now that element is dynamically created
  src/www/app/app.ts
Labels: size/XS

#1747 fix(www): always send the build number as a tag to Sentry
  src/www/app/cordova_main.ts
Labels: size/XS

#1748 feat(www): add a form field to distinguish new style form submissions in salesforce
  src/www/shared/error_reporter.ts
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
Labels: size/XS

#1746 feat(www): polish the contact view UI
  src/www/ui_components/app-root.js
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
  src/www/views/contact_view/stories.ts
Labels: size/M

#1750 chore: replace all pngs with svgs now that we've moved to catalyst
  src/www/assets/icons/about.png
  src/www/assets/icons/add.png
  src/www/assets/icons/back.png
  src/www/assets/icons/change_language.png
  src/www/assets/icons/contact.png
  src/www/assets/icons/feedback.png
  src/www/assets/icons/help.png
  src/www/assets/icons/menu.png
  src/www/assets/icons/outline.png
  src/www/assets/icons/quit.png
  src/www/assets/jigsaw-logo.png
  src/www/assets/outline-client-logo.png
  src/www/ui_components/about-view.js
  src/www/ui_components/app-root.js
Labels: size/S

#1756 chore(cordova/apple): remove iPad for macOS
  src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
Labels: size/XS

#1751 feat(www): change style to filled fields to stay consistent with other text fields
  src/www/ui_components/server-rename-dialog.js
  src/www/views/contact_view/index.spec.ts
  src/www/views/contact_view/index.ts
  src/www/views/contact_view/support_form/index.ts
  src/www/views/shared/card/index.ts
  src/www/views/shared/card/stories.ts
Labels: size/L

#1763 fix(electron): 🩹 fix connection issue of domain name keys
  src/electron/connectivity.ts
  src/electron/index.ts
Labels: size/XS
