Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-08, with the labels that each got.

#2090 refactor(client): clean up App Groups
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/VpnExtension.entitlements
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/ios/Outline/Classes/AppKitBridge/AppKitController.swift
  client/src/cordova/apple/xcode/ios/Outline/Outline.entitlements
  client/src/cordova/apple/xcode/macos/OutlineLauncher/AppDelegate.swift
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
Labels: size/XS

#2105 refactor(client): decouple Typescript VPN API from individual servers
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/routing_service.ts
  client/electron/tunnel_store.ts
  client/electron/vpn_tunnel.ts
  client/src/cordova/android/README.md
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineTunnel.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline/Classes/AppDelegate.m
  client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
  client/src/www/app/app.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/main.ts
  client/src/www/app/outline_server_repository/access_key_serialization.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.electron.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/outline_server_repository/vpn.electron.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
  client/src/www/app/outline_server_repository/vpn.ts
  client/src/www/app/platform.ts
  client/src/www/model/events.ts
Labels: size/XXL

#2110 chore(client): add missing packages and fix some lint issues
  client/package.json
  client/src/www/app/clipboard.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/url_interceptor.ts
  package-lock.json
Labels: size/XS

#2113 refactor(client): clean up Apple VPN code
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineSentryLogger/OutlineSentryLogger.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineTunnel.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineAppleLib/Tests/OutlineTunnelTest/OutlineTunnelTest.swift
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
Labels: size/XL

#2059 ci: add license check to ensure we only depend on 'notice' licenses
  .github/workflows/build_and_test_debug_client.yml
  .github/workflows/license.yml
  .prettierrc.js
  Taskfile.yml
  go.mod
  go.sum
  package.json
  tools.go
Labels: size/XL

#2117 fix(client): properly wait for start to be done
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
Labels: size/S

#2114 refactor(client): delete OutlineLauncher and OutlineTunnelStore
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineCatalystApp/CatalystApp.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineCatalystApp/NSObject+Outline.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineLauncher/AppDelegate.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineTunnelStore.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineAppleLib/Tests/OutlineTunnelTest/OutlineTunnelTest.swift
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/xcshareddata/xcschemes/OutlineLauncher.xcscheme
  client/src/cordova/apple/xcode/macos/Outline/Classes/AppDelegate.m
  client/src/cordova/apple/xcode/macos/OutlineLauncher/AppDelegate.swift
  client/src/cordova/apple/xcode/macos/OutlineLauncher/Base.lproj/Main.storyboard
  client/src/cordova/apple/xcode/macos/OutlineLauncher/Info.plist
  client/src/cordova/apple/xcode/macos/OutlineLauncher/OutlineLauncher.entitlements
Labels: size/XL

#2132 feat(client): support IPv6 on Apple, pass transport config around as string in Apple code
  client/go/outline/shadowsocks/client.go
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/Subnet.swift
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/project.pbxproj
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/xcshareddata/xcschemes/VpnExtension.xcscheme
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/xcshareddata/xcschemes/VpnExtensionTest.xcscheme
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.swift
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/VpnExtension-Bridging-Header.h
  client/src/cordova/apple/OutlineLib/VpnExtensionTest/VpnExtensionTest.swift
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
  client/src/cordova/test.action.mjs
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
Labels: size/XL

#2140 chore(client): update Android README
  client/src/cordova/android/README.md
Labels: size/XS

#2141 chore(client): pass transport as string on Android and Apple
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/TunnelConfig.aidl
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
  client/src/www/app/outline_server_repository/vpn.cordova.ts
Labels: size/M

#2145 chore(client): add new messages for contact view option
  client/resources/original_messages.json
Labels: size/XS

#2147 fix(client): fix styling of the splash screen
  client/src/www/style.css
  client/src/www/views/root_view/privacy_acknowledgement_dialog/index.ts
Labels: size/XS

#2152 chore(manager): delete dead S3 invite code
  server_manager/www/app.ts
  server_manager/www/ui_components/app-root.ts
  server_manager/www/ui_components/outline-share-dialog.ts
Labels: size/S

#2154 chore(client): remove duplicate "Cancel" message
  client/resources/original_messages.json
  client/src/www/views/root_view/add_access_key_dialog/index.ts
Labels: size/XS

#2144 feat(client): link to locale-aware support site pages
  client/src/www/ui_components/app-root.js
  client/src/www/views/contact_view/index.ts
  client/src/www/views/language_view/index.ts
  client/src/www/views/root_view/privacy_acknowledgement_dialog/index.ts
Labels: size/L

#2153 refactor(client): simplify Go PlatformError and marshalling logic
  client/go/outline/electron/main.go
  client/go/outline/platerrors/marshal.go
  client/go/outline/platerrors/marshal_test.go
  client/go/outline/platerrors/platform_error.go
  client/go/outline/platerrors/platform_error_test.go
  client/go/outline/shadowsocks/client.go
  client/go/outline/shadowsocks/config.go
  client/src/www/model/platform_error.ts
Labels: size/L

#2142 chore(client): pass transport as string in electron, to the extent possible
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/tunnel_store.ts
  client/go/outline/electron/main.go
  client/src/www/app/outline_server_repository/vpn.electron.ts
Labels: size/M

#2186 Revert "refactor(manager): output folder cleanup (#2083)"
  server_manager/README.md
  server_manager/base.webpack.js
  server_manager/electron/build.action.sh
  server_manager/electron/package.action.sh
  server_manager/electron/start.action.sh
  server_manager/electron_main.webpack.mjs
  server_manager/electron_preload.webpack.mjs
  server_manager/test.action.sh
  server_manager/www/build.action.sh
  server_manager/www/build_install_script.action.sh
  server_manager/www/start.action.sh
  server_manager/www/test.action.sh
Labels: size/XS

#2182 refactor(client): replace references to Shadowsocks
  client/electron/go_vpn_tunnel.ts
  client/electron/linux_proxy_controller/outline_error.cpp
  client/electron/linux_proxy_controller/outline_error.h
  client/go/Taskfile.yml
  client/go/outline/client.go
  client/go/outline/client_test.go
  client/go/outline/config.go
  client/go/outline/config_test.go
  client/go/outline/connectivity/connectivity.go
  client/go/outline/electron/main.go
  client/go/outline/neterrors/neterrors.go
  client/go/outline/shadowsocks/client.go
  client/go/outline/tun2socks/tcp.go
  client/go/outline/tun2socks/tunnel.go
  client/go/outline/tun2socks/tunnel_android.go
  client/go/outline/tun2socks/tunnel_darwin.go
  client/go/outline/tun2socks/udp.go
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/shadowsocks/ShadowsocksConfig.aidl
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnel.java
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.h
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.swift
Labels: size/L
