Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-05, with the labels that each got.

#2002 fix(manager): remove duplicate message
  server_manager/messages/master_messages.json
  server_manager/web_app/ui_components/outline-support-form.ts
Labels: size/XS

#2018 fix(manager): add missing messages and improve style slightly
  server_manager/messages/master_messages.json
  server_manager/web_app/ui_components/outline-contact-us-dialog.ts
Labels: size/XS

#2019 fix(client): update more broken paths
  .eslintrc.json
  client/src/cordova/android/README.md
  client/src/cordova/apple/README.md
  client/src/www/ui_components/licenses/README.md
Labels: size/XS

#2020 refactor(client): move `app_paths.ts` to `client/electron`
  client/electron/app_paths.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/routing_service.ts
  client/tsconfig.json
Labels: size/XS

#2009 chore(client/cordova/apple/ios): add privacy info to comply with Apple's API changes
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineSentryLogger/OutlineSentryLogger.swift
  client/src/cordova/apple/ios.xcworkspace/xcshareddata/swiftpm/Package.resolved
  client/src/cordova/apple/macos.xcworkspace/xcshareddata/swiftpm/Package.resolved
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  client/src/cordova/apple/xcode/ios/PrivacyInfo.xcprivacy
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
Labels: size/S

#2023 chore(client): remove deprecated feedback form
  client/resources/original_messages.json
  client/src/www/TODO.spec.ts
  client/src/www/app/app.ts
  client/src/www/model/errors.ts
  client/src/www/ui_components/app-root.js
  client/src/www/ui_components/feedback-view.js
Labels: size/L

#2024 style(manager/mac): resize icon for macOS
  client/package.json
  package-lock.json
  server_manager/README.md
  server_manager/electron_app/build.action.sh
  server_manager/electron_app/icons/mac/icon.icns
  server_manager/electron_app/icons/png/1024x1024.png
  server_manager/electron_app/icons/png/128x128.png
  server_manager/electron_app/icons/png/16x16.png
  server_manager/electron_app/icons/png/24x24.png
  server_manager/electron_app/icons/png/256x256.png
  server_manager/electron_app/icons/png/32x32.png
  server_manager/electron_app/icons/png/48x48.png
  server_manager/electron_app/icons/png/512x512.png
  server_manager/electron_app/icons/png/64x64.png
  server_manager/electron_app/icons/win/icon.ico
  server_manager/package.json
Labels: size/XS

#2026 test(client): fix failed tun2socks connectivity_test cases
  .github/workflows/build_and_test_debug_client.yml
  client/src/tun2socks/outline/connectivity/connectivity_test.go
Labels: size/XS

#2027 fix(client/electron): set productName
  client/electron/electron-builder.json
Labels: size/XS

#2028 fix(docs): fix links to the right stable versions
  docs/invitation_instructions.md
Labels: size/XS
