Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-09, with the labels that each got.

#2198 docs(client): update required Go to 1.21
  client/README.md
Labels: size/XS

#2192 refactor(client): clean up transport in Typescript
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/tunnel_store.ts
  client/src/www/app/app.ts
  client/src/www/app/outline_server_repository/access_key.ts
  client/src/www/app/outline_server_repository/access_key_serialization.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/outline_server_repository/vpn.electron.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
  client/src/www/app/outline_server_repository/vpn.spec.ts
  client/src/www/app/outline_server_repository/vpn.ts
  client/src/www/model/errors.ts
  client/src/www/model/server.ts
  client/src/www/views/root_view/add_access_key_dialog/index.ts
  infrastructure/net.spec.ts
  infrastructure/net.ts
Labels: size/XL

#2191 fix(manager): do not error on non-semantic versions
  server_manager/www/app.spec.ts
  server_manager/www/app.ts
  server_manager/www/shadowbox_server.ts
  server_manager/www/testing/models.ts
Labels: size/S

#2146 feat(client): add new contact us option for billing issues
  client/src/www/views/contact_view/index.spec.ts
  client/src/www/views/contact_view/index.ts
Labels: size/S

#2204 fix(client): fix dynamic key parsing
  client/src/www/app/outline_server_repository/server.spec.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.ts
Labels: size/S

#2205 refactor(client): use new Go API for electron
  client/electron/go_vpn_tunnel.ts
  client/electron/process.ts
  client/go/outline/electron/main.go
Labels: size/M

#2214 fix(client/windows): restore product name to "Outline"
  client/electron/electron-builder.json
Labels: size/XS

#2218 fix(client/linux): use new installation error and service path
  client/electron/app_paths.ts
  client/electron/preload.ts
  client/electron/routing_service.ts
  client/src/www/app/app.ts
  client/src/www/model/platform_error.ts
Labels: size/M
