Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-07, with the labels that each got.

#2045 ci(manager/mac): use `macos-13` as the CI runner
  .github/workflows/build_and_test_debug_manager.yml
Labels: size/XS

#2044 docs(client/cordova/android): update paths and remove outdated info
  client/src/cordova/android/README.md
Labels: size/XS

#2046 fix(client/cordova/android): show Outline logo in splash screen
  client/config.xml
  client/resources/splashscreen/android/splash_screen_icon_xxxhdpi.png
  client/resources/splashscreen/android/splashscreen_hdpi.png
  client/resources/splashscreen/android/splashscreen_xhdpi.png
  client/resources/splashscreen/android/splashscreen_xxhdpi.png
  client/resources/splashscreen/android/splashscreen_xxxhdpi.png
Labels: size/XS

#2055 build: add missing dependency
  package-lock.json
  package.json
Labels: size/XS

#2054 refactor(client/cordova/android): remove dead reachability test code
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
  client/src/tun2socks/outline/shadowsocks/client.go
Labels: size/XS

#1998 fix(src/build): output child process stderr to console.error
  src/build/spawn_stream.mjs
Labels: size/S

#2060 ci: run CI job daily so we catch issues with runner changes
  .github/workflows/build_and_test_debug_client.yml
  .github/workflows/build_and_test_debug_manager.yml
Labels: size/XS

#1787 chore(client/cordova/apple): introduce XCode subproject
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineAppleLib/Tests/OutlineTunnelTest/OutlineTunnelTest.swift
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/project.pbxproj
  client/src/cordova/apple/OutlineLib/VpnExtension/Info.plist
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.h
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/VpnExtension.entitlements
  client/src/cordova/apple/README.md
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist
  client/src/cordova/apple/xcode/ios/Outline/VpnExtension.entitlements
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist
  client/src/cordova/apple/xcode/macos/Outline/VpnExtension.entitlements
Labels: size/XXL

#2071 refactor(client/cordova/apple): assorted cleanups
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineNotification/NSNotification+Outline.swift
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj
  client/src/cordova/apple/xcode/macos/Outline/Classes/AppDelegate.m
  client/src/cordova/apple/xcode/macos/Outline/Classes/CDVMacOsUrlHandler.swift
  client/src/cordova/apple/xcode/macos/Outline/Classes/EventMonitor.swift
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
Labels: size/M

#2072 refactor(client): revamp Tunnel code
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/routing_service.ts
  client/electron/tunnel_store.ts
  client/electron/vpn_tunnel.ts
  client/src/cordova/android/README.md
  client/src/www/TODO.spec.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/main.ts
  client/src/www/app/outline_server_repository/access_key_serialization.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.cordova.ts
  client/src/www/app/outline_server_repository/server.electron.ts
  client/src/www/app/outline_server_repository/server.fake.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/platform.ts
  client/src/www/app/plugin.cordova.ts
  client/src/www/app/tunnel.ts
  client/src/www/app/url_interceptor.ts
  client/src/www/webpack_cordova.mjs
  client/src/www/webpack_electron.mjs
Labels: size/L
