Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-04, with the labels that each got.

#1940 chore(client/electron/linux): remove the "Beta" from the title bar
  src/www/index_electron.html
Labels: size/XS

#1948 fix(build): fix Outline Client build in Windows
  package-lock.json
  package.json
  src/infrastructure/electron/app_paths.ts
  src/tun2socks/build.action.mjs
Labels: size/XS

#1957 build(client/electron/windows): delete unused find_tap_name
  client/tools/find_tap_name/bin/386/find_tap_name.exe
  client/tools/find_tap_name/bin/amd64/find_tap_name.exe
  client/tools/find_tap_name/build.action.sh
  client/tools/find_tap_name/main.go
  src/electron/find_tap_device_name.bat
Labels: size/M

#1952 build(client/electron): build Windows with MinGW
  Makefile
  package-lock.json
  src/electron/README.md
Labels: size/XS

#1949 fix(www): add alternative access key message to the translation pipeline
  client/resources/original_messages.json
Labels: size/XS

#1941 chore(www): upgrade `servers-view` to Lit
  client/src/www/app/app.ts
  client/src/www/ui_components/app-root.js
  client/src/www/views/servers_view/index.ts
Labels: size/M

#1963 fix(client/electron): fix tray icon
  src/electron/electron-builder.json
  src/electron/index.ts
Labels: size/XS

#1960 build(client/electron): build cross-platform with zig
  Makefile
  src/electron/README.md
Labels: size/XS

#1967 build(client): use Taskfile for tun2socks
  .gitignore
  Makefile
  Taskfile.yml
  client/src/tun2socks/Taskfile.yml
  client/src/tun2socks/build.action.mjs
  go.mod
  go.sum
  package.json
  tools.go
Labels: size/L

#1970 fix(manager): fix Karma test for server_manager
  server_manager/web_app/test.action.sh
Labels: size/XS

#1969 docs(docs): update README now client has moved into `/client` directory
  README.md
  client/README.md
  docs/resources/logo_client.png
  docs/resources/logo_manager.png
Labels: size/S

#1989 chore(manager): remove unused `package-lock.json`
  server_manager/package-lock.json
Labels: size/XXL

#1992 fix(client/electron/windows): force `eol=crlf` for Windows installation scripts
  .gitattributes
Labels: size/XS

#1993 fix(client/electron/windows): normalize crlf line endings
  .gitattributes
  src/electron/custom_install_steps.nsh
  third_party/tap-windows6/bin/amd64/OemVista.inf
  third_party/tap-windows6/bin/i386/OemVista.inf
  third_party/tap-windows6/bin/include/tap-windows.h
Labels: size/L

#1997 fix(client/electron): update electron's tun2socks paths built by taskfile
  client/infrastructure/electron/app_paths.ts
  src/electron/electron-builder.json
  src/electron/go_vpn_tunnel.ts
  src/electron/routing_service.ts
Labels: size/XS

#2000 feat(client): disable TCP Keep-Alive to save battery
  client/src/tun2socks/outline/shadowsocks/client.go
Labels: size/XS
