Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-10, with the labels that each got.

#2226 chore(client,manager): add new messages for consent form option
  .github/workflows/pull_request_checks.yml
  client/resources/original_messages.json
  server_manager/messages/master_messages.json
Labels: size/XS

#2232 ci(devtools): fix PR commitlint workflow
  .github/workflows/pull_request_checks.yml
Labels: size/XS

#2210 feat(client/ios): propagate structured errors from Go to TypeScript
  client/go/Taskfile.yml
  client/go/outline/client.go
  client/go/outline/client_test.go
  client/go/outline/connectivity/connectivity.go
  client/go/outline/electron/main.go
  client/go/outline/neterrors/neterrors.go
  client/go/outline/tun2socks/tunnel_darwin.go
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineError/OutlineError.swift
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineTunnel/OutlineVpn.swift
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/project.pbxproj
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.swift
  client/src/cordova/apple/OutlineLib/VpnExtensionTest/VpnExtensionTest.swift
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
Labels: size/XXL

#2231 feat(client): add new outreach consent option to support form
  client/src/www/views/contact_view/index.spec.ts
  client/src/www/views/contact_view/index.ts
  client/src/www/views/contact_view/support_form/index.ts
  client/src/www/views/contact_view/support_form/stories.ts
Labels: size/S

#2227 feat(manager): add new outreach consent option to support form
  server_manager/www/browser_main.ts
  server_manager/www/ui_components/outline-contact-us-dialog.ts
  server_manager/www/ui_components/outline-support-form.ts
Labels: size/S

#2251 fix(client/ios): filter `AppKitIntegration` framework to `maccatalyst`
  client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj
Labels: size/XS

#2253 fix(client/ios): remove AppIcon.appiconset
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-1024.png
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-128.png
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-16.png
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-256.png
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-32.png
  client/src/cordova/apple/xcode/ios/Outline/Assets.xcassets/AppIcon.appiconset/icon-512.png
Labels: size/XS

#2248 fix(devtools): correct paths in Android release scripts
  client/src/cordova/build.action.mjs
  client/src/cordova/setup.action.mjs
Labels: size/XS
