Repository Jigsaw-Code/outline-apps, pull requests merged in 2024-11, with the labels that each got.

#2220 refactor(client/windows): move fetching logic from TypeScript to Go
  client/electron/go_helpers.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/go/outline/electron/main.go
  client/go/outline/fetch.go
  client/go/outline/fetch_test.go
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/main.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/platform.ts
  client/src/www/app/resource_fetcher.electron.ts
  client/src/www/app/resource_fetcher.ts
Labels: size/L

#2221 refactor(client/android): move fetching logic from TypeScript to Go
  client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
  client/src/www/app/main.cordova.ts
  client/src/www/app/resource_fetcher.cordova.ts
Labels: size/XS

#2255 feat(client/linux): generate Debian package
  client/electron/app_paths.ts
  client/electron/debian/after_install.sh
  client/electron/electron-builder.json
Labels: size/XS

#2265 refactor(client): more config cleanup and consolidation
  client/electron/go_helpers.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/src/www/app/app.ts
  client/src/www/app/outline_server_repository/access_key.ts
  client/src/www/app/outline_server_repository/config.spec.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.spec.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
  client/src/www/app/outline_server_repository/vpn.spec.ts
  client/src/www/app/outline_server_repository/vpn.ts
  client/src/www/views/root_view/add_access_key_dialog/index.ts
Labels: size/XL

#2269 refactor(client): reduce config library surface
  client/electron/index.ts
  client/src/www/app/app.ts
  client/src/www/app/outline_server_repository/config.spec.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
Labels: size/L

#2222 refactor(client/ios): move fetching logic from TypeScript to Go
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
  client/src/www/app/main.cordova.ts
Labels: size/S

#2263 feat(client/windows): introduce go plugin to call `fetchResource` as a library
  .github/workflows/build_and_test_debug_client.yml
  client/electron/app_paths.ts
  client/electron/electron-builder.json
  client/electron/go_helpers.ts
  client/electron/go_plugin.ts
  client/electron/index.ts
  client/electron/webpack_electron_main.mjs
  client/go/Taskfile.yml
  client/go/outline/electron/go_plugin.go
  client/go/outline/electron/main.go
  client/package.json
  client/src/www/app/resource_fetcher.electron.ts
  package-lock.json
Labels: os/windows, os/linux, size/L
