Repository Jigsaw-Code/outline-apps, pull requests merged in 2025-02, with the labels that each got.

#2330 feat(client): add callback/event mechanism between TypeScript and Go
  client/electron/go_plugin.ts
  client/electron/index.ts
  client/electron/vpn_service.ts
  client/go/outline/callback/callback.go
  client/go/outline/callback/callback_test.go
  client/go/outline/electron/go_plugin.go
  client/go/outline/method_channel.go
  client/go/outline/vpn/vpn.go
  client/go/outline/vpn_linux.go
  client/go/outline/vpn_others.go
Labels: size/XL

#2355 fix(client/linux): update TUN and IP to avoid conflicts with legacy routing
  client/electron/vpn_service.ts
  client/go/outline/vpn/vpn_linux.go
Labels: size/XS

#2357 fix: introduce first-supported Endpoint
  client/config.md
  client/go/outline/config/config_first_supported.go
  client/go/outline/config/module.go
Labels: size/S

#2360 feat(client): support Shadowsocks prefix for UDP
  client/go/outline/config/config_shadowsocks.go
  go.mod
  go.sum
Labels: size/XS

#2363 fix(client): enforce no proxyless
  client/go/outline/client.go
  client/go/outline/client_test.go
  client/go/outline/platerrors/platform_error.go
  client/go/outline/platerrors/platform_error_test.go
Labels: size/XS

#2353 chore(client): add platform check to Cordova build script
  client/src/cordova/build.action.mjs
Labels: size/XS

#2364 fix(client/linux): delete TUN device and NM connections when disconnect
  client/go/outline/vpn/nm_retry.go
  client/go/outline/vpn/nmconn_linux.go
  client/go/outline/vpn/tun_linux.go
  client/go/outline/vpn/vpn_linux.go
Labels: size/L

#2366 fix(client/linux): add timeout for CloseVPN
  client/go/outline/vpn/vpn.go
Labels: size/XS

#2362 feat(client/windows): enable WebSocket
  client/electron/go_helpers.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/routing_service.ts
  client/electron/windows/OutlineService/OutlineService/OutlineService.cs
  client/electron/windows/OutlineService/OutlineService/OutlineService.csproj
  client/electron/windows/OutlineService/OutlineService/bin/OutlineService.exe
  client/go/outline/client.go
  client/go/outline/config/config_dial_endpoint.go
  client/go/outline/config/module.go
  client/go/outline/electron/dialer_others.go
  client/go/outline/electron/dialer_windows.go
  client/go/outline/electron/main.go
  client/go/outline/vpn_linux.go
Labels: size/L

#2370 build(client/windows): code sign dependent binaries included in NSIS
  client/electron/build.action.mjs
Labels: size/XS

#2380 fix(client): fix parsing of legacy JSON
  client/go/outline/config/config_dial_endpoint.go
  client/go/outline/config/parse.go
  client/go/outline/parse.go
  client/go/outline/parse_test.go
  go.mod
  go.sum
Labels: size/M

#2381 build(client/windows): check in signed binaries, revert build-time signing
  client/electron/build.action.mjs
  client/electron/windows/OutlineService/OutlineService/bin/OutlineService.exe
  client/electron/windows/smartdnsblock/bin/smartdnsblock.exe
Labels: size/XS

#2404 fix(manager/macos): address auto-update regression
  server_manager/README.md
  server_manager/electron/electron_builder.json
Labels: size/XS
