Repository Jigsaw-Code/outline-apps, pull requests merged in 2025-01, with the labels that each got.

#2317 ci: fix Chromium sandbox issue of manager web test
  .github/workflows/build_and_test_debug_manager.yml
Labels: size/XS

#2316 ci: switch to advanced setup for code scanning
  .github/workflows/codeql.yml
Labels: size/S

#2291 feat(client/linux): revamp the Linux VPN routing logic
  .github/workflows/license.yml
  client/electron/debian/after_install.sh
  client/electron/electron-builder.json
  client/electron/go_plugin.ts
  client/electron/index.ts
  client/electron/vpn_service.ts
  client/go/outline/client.go
  client/go/outline/connectivity.go
  client/go/outline/connectivity/connectivity.go
  client/go/outline/dialer_linux.go
  client/go/outline/method_channel.go
  client/go/outline/platerrors/error_code.go
  client/go/outline/vpn/device.go
  client/go/outline/vpn/errors.go
  client/go/outline/vpn/nmconn_linux.go
  client/go/outline/vpn/tun_linux.go
  client/go/outline/vpn/vpn.go
  client/go/outline/vpn/vpn_linux.go
  client/go/outline/vpn/vpn_others.go
  client/go/outline/vpn_linux.go
  client/go/outline/vpn_others.go
  go.mod
  go.sum
Labels: os/linux, size/XXL

#2324 refactor(client): make parsing async and config an opaque string
  client/electron/go_helpers.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/vpn_service.ts
  client/src/cordova/plugin/apple/src/OutlinePlugin.swift
  client/src/www/app/app.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.ts
  client/src/www/app/outline_server_repository/config.spec.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/index.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
  client/src/www/model/server.ts
  client/src/www/views/contact_view/support_form/index.spec.ts
  client/src/www/views/root_view/add_access_key_dialog/index.ts
  infrastructure/net.spec.ts
  infrastructure/net.ts
Labels: size/XXL

#2336 chore(client): clean up invokeMethod error propagation
  client/electron/go_plugin.ts
  client/electron/index.ts
  client/electron/vpn_service.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/outline_server_repository/vpn.electron.ts
Labels: size/M

#2343 docs(client/windows): add build requirements for Windows machines
  client/electron/README.md
Labels: size/XS

#2346 chore(client): clean up errors
  client/electron/routing_service.ts
  client/src/www/app/app.ts
  client/src/www/app/error_localizer.ts
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/plugin.cordova.ts
  client/src/www/model/errors.ts
  client/src/www/model/platform_error.ts
Labels: size/L

#2329 feat(client): introduce extensible YAML config
  client/config.md
  client/go/outline/client.go
  client/go/outline/client_test.go
  client/go/outline/config.go
  client/go/outline/config/config_dial_endpoint.go
  client/go/outline/config/config_shadowsocks.go
  client/go/outline/config/config_shadowsocks_test.go
  client/go/outline/config/config_tcpudp.go
  client/go/outline/config/module.go
  client/go/outline/config/module_test.go
  client/go/outline/config/parse.go
  client/go/outline/config/types.go
  client/go/outline/config/utf8.go
  client/go/outline/config/utf8_test.go
  client/go/outline/config_test.go
  client/go/outline/dialer_linux.go
  client/go/outline/electron/main.go
  client/go/outline/method_channel.go
  client/go/outline/parse.go
  client/go/outline/parse_test.go
  client/go/outline/platerrors/error_code.go
  client/go/outline/vpn/errors.go
  client/go/outline/vpn/vpn_linux.go
  client/go/outline/vpn_linux.go
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/apple/OutlineAppleLib/Sources/OutlineError/OutlineError.swift
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.swift
  client/src/www/app/main.cordova.ts
  client/src/www/app/main.electron.ts
  client/src/www/app/outline_server_repository/config.spec.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
  client/src/www/app/plugin.cordova.ts
  client/src/www/model/platform_error.ts
  go.mod
  go.sum
Labels: size/XXL

#2309 fix(client/ios): update minimum deployment target to `15.5`
  client/go/Taskfile.yml
  client/src/cordova/apple/OutlineAppleLib/Package.swift
  client/src/cordova/apple/OutlineLib/OutlineLib.xcodeproj/project.pbxproj
Labels: size/XS

#2351 feat(client): add Websocket support to the Outline Client config
  client/config.md
  client/go/outline/client_test.go
  client/go/outline/config/config_websocket.go
  client/go/outline/config/module.go
  go.mod
  go.sum
Labels: size/M

#2356 fix(client/linux): resolve proxy address before connection
  client/go/outline/config/config_dial_endpoint.go
Labels: size/XS
