Repository Jigsaw-Code/outline-apps, pull requests merged in 2025-08, with the labels that each got.

#2579 fix(client): fix config marshaling
  client/go/configyaml/parse.go
  client/go/outline/config/config_shadowsocks_test.go
  client/go/outline/parse.go
  client/go/outline/parse_test.go
Labels: size/L

#2581 chore(client): clean up client config
  client/electron/index.ts
  client/electron/tunnel_store.ts
  client/electron/vpn_service.ts
  client/go/outline/vpn_linux.go
  client/src/www/app/outline_server_repository/config.spec.ts
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/outline_server_repository/vpn.fake.ts
  client/src/www/app/outline_server_repository/vpn.ts
  client/tsconfig.json
Labels: size/M

#2585 refactor(client): introduce Start/EndSession
  client/go/outline/client.go
  client/go/outline/electron/main.go
  client/go/outline/method_channel.go
  client/go/outline/tun2socks/tunnel.go
  client/go/outline/vpn/vpn.go
  client/go/outline/vpn_linux.go
  client/go/outline/vpn_others.go
  client/src/cordova/android/README.md
Labels: size/M

#2591 fix(client): don't run Reporter when absent
  client/go/outline/client.go
Labels: size/XS

#2604 docs(client): update android studio documentation
  client/src/cordova/android/README.md
Labels: size/XS

#2606 fix(client): allow adding keys with unresolvable hostnames
  client/go/outline/config/config_dial_endpoint.go
Labels: size/XS

#2617 chore(devtools): use go tool
  .github/workflows/license.yml
  Taskfile.yml
  client/go/build.action.mjs
  client/tsconfig.json
  go.mod
  go.sum
  package.json
  tools.go
Labels: size/L
