Repository Jigsaw-Code/outline-apps, pull requests merged in 2025-06, with the labels that each got.

#2516 fix(client): incorrect server status after adding/forgetting servers
  client/src/www/app/app.ts
Labels: size/XS

#2507 chore(client): encapsulate client config
  .github/workflows/build_and_test_debug_client.yml
  client/electron/go_helpers.ts
  client/electron/go_vpn_tunnel.ts
  client/electron/index.ts
  client/electron/vpn_service.ts
  client/go/outline/client.go
  client/go/outline/client_test.go
  client/go/outline/electron/main.go
  client/go/outline/method_channel.go
  client/go/outline/parse.go
  client/go/outline/parse_test.go
  client/go/outline/vpn_linux.go
  client/src/www/app/outline_server_repository/config.ts
  client/src/www/app/outline_server_repository/server.ts
  client/src/www/app/outline_server_repository/vpn.cordova.ts
  client/src/www/app/outline_server_repository/vpn.ts
Labels: size/XL

#2519 refactor(client): clean up tunnel layer
  client/go/outline/tun2socks/tunnel.go
  client/go/outline/tun2socks/tunnel_android.go
  client/go/tunnel/tun.go
  client/go/tunnel/tun_android.go
  client/go/tunnel/tunnel.go
Labels: size/M

#2529 fix(client/linux): upgrade Koffi to resolve bundle issue
  client/package.json
  package-lock.json
Labels: size/XS
