Repository Jigsaw-Code/outline-apps, pull requests merged in 2025-09, with the labels that each got.

#2628 refactor(client/android): migrate to `vpn` API and remove connectivity test
  client/go/outline/connectivity/connectivity.go
  client/go/outline/tun2socks/device.go
  client/go/outline/tun2socks/init_mobile.go
  client/go/outline/tun2socks/relay_unix.go
  client/go/outline/tun2socks/tunnel_android.go
  client/go/outline/tun2socks/tunnel_darwin.go
  client/go/outline/vpn/device.go
  client/go/outline/vpn/relay.go
  client/go/outline/vpn/vpn.go
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
  client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelStore.java
Labels: size/XL

#2630 refactor(client/ios): migrate to `vpn` API and remove connectivity test
  client/go/outline/connectivity.go
  client/go/outline/tun2socks/device.go
  client/go/outline/tun2socks/relay.go
  client/go/outline/tun2socks/tcp.go
  client/go/outline/tun2socks/tunnel.go
  client/go/outline/tun2socks/tunnel_darwin.go
  client/go/outline/tun2socks/udp.go
  client/src/cordova/apple/OutlineLib/VpnExtension/Sources/PacketTunnelProvider.m
Labels: size/L

#2618 fix(client/ios): make images non-selectable
  client/web/views/about_view/index.ts
  client/web/views/root_view/privacy_acknowledgement_dialog/index.ts
  client/web/views/root_view/root_navigation/index.ts
  client/web/views/servers_view/server_connection_indicator/index.ts
  client/web/views/servers_view/server_list_item/server_card/server_info_dialog/index.ts
Labels: size/XS

#2640 feat(client): add block/direct PacketDialers and direct PacketListener
  client/go/outline/config/config_block.go
  client/go/outline/config/config_block_test.go
  client/go/outline/config/module.go
Labels: size/S
